config/routes.rb
Rails.application.routes.draw do

  root 'store#index', as: 'store'

  resources :entrees

end

app/models/entree.rb
class Entree < ActiveRecord::Base
  validates :food_item, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :food_item, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be a URL for GIF, JPG or PNG image."
  }

  def self.latest
    Entree.order(:updated_at).last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/entrees_controller.rb
class EntreesController < ApplicationController
  before_action :set_entree, only: [:show, :edit, :update, :destroy]

  # GET /entrees
  # GET /entrees.json
  def index
    @entrees = Entree.all
  end

  # GET /entrees/1
  # GET /entrees/1.json
  def show
  end

  # GET /entrees/new
  def new
    @entree = Entree.new
  end

  # GET /entrees/1/edit
  def edit
  end

  # POST /entrees
  # POST /entrees.json
  def create
    @entree = Entree.new(entree_params)

    respond_to do |format|
      if @entree.save
        format.html { redirect_to @entree, notice: 'Entree was successfully created.' }
        format.json { render :show, status: :created, location: @entree }
      else
        format.html { render :new }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrees/1
  # PATCH/PUT /entrees/1.json
  def update
    respond_to do |format|
      if @entree.update(entree_params)
        format.html { redirect_to @entree, notice: 'Entree was successfully updated.' }
        format.json { render :show, status: :ok, location: @entree }
      else
        format.html { render :edit }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrees/1
  # DELETE /entrees/1.json
  def destroy
    @entree.destroy
    respond_to do |format|
      format.html { redirect_to entrees_url, notice: 'Entree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entree
      @entree = Entree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entree_params
      params.require(:entree).permit(:food_item, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @entrees = Entree.order(:food_item) # "order" Lists order alphebetically.

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrees_helper.rb
module EntreesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/entrees/_form.html.erb
<%= form_for(@entree) do |f| %>
  <% if @entree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entree.errors.count, "error") %> prohibited this entree from being saved:</h2>

      <ul>
      <% @entree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_item %><br>
    <%= f.text_field :food_item %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entrees/edit.html.erb
<h1>Editing entree</h1>

<%= render 'form' %>

<%= link_to 'Show', @entree %> |
<%= link_to 'Back', entrees_path %>

app/views/entrees/index.html.erb
<h1>Main menu</h1>


<div class="row">
  <% @entrees.each do |entree| %>
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(entree.image_url, class: "list-image", alt: "picture") %>
      <div class="caption">
        <h3><%= entree.food_item %></h3>
        <p><%= truncate(strip_tags(entree.description), class: "list-description", length: 80) %></p>
        <p class="price"><%= number_to_currency(entree.price) %></p>
        <%= link_to 'Show', entree, class: "btn btn-default", role: "button" %>
        <%= link_to 'Edit', edit_entree_path(entree), class: "btn btn-default", role: "button" %>
        <%= link_to 'Destroy', entree, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default", role: "button"%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/entrees/new.html.erb
<h1>New entree</h1>

<%= render 'form' %>

<%= link_to 'Back', entrees_path %>

app/views/entrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food item:</strong>
  <%= @entree.food_item %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entree.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @entree.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @entree.price %>
</p>

<%= link_to 'Edit', edit_entree_path(@entree) %> |
<%= link_to 'Back', entrees_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
</div>

<div class="footer-links">
  <small>Date and Time: </small><%= Time.now %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "Buzzy's", "#", class: "navbar-brand" %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Main menu', "#" %></li>
        <li><%= link_to 'New Entree', new_entree_path %></li>
        <li><%= link_to 'Contact', "#" %></li>
        <li><%= link_to "Sign in", "#" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cashier</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<div class="container">
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/store/index.html.erb
<% if notice %>
<p id="notice"><% notice %></p>
<% end %>

<h1>Buzzy's Main menu</h1>

<% cache ['store', Entree.latest] do %>
  <div class="row">
    <% @entrees.each do |entree| %>
      <% cache ["entry", entree] do %>
        <div class="col-xs-6 col-md-3">
          <div class="thumbnail">
            <%= image_tag(entree.image_url, class: "list-image", alt: "Picture") %>
            <div class="caption">
            <h3><%= entree.food_item %></h3>
            <%= sanitize(entree.description, class: "list-description") %>
            <span class="price"><%= number_to_currency(entree.price) %></span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>